# Overall Project

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# =============================================================================
# NCAAB TRAINING DATA GENERATOR
# Scrapes CBS Sports scoreboard for Feb 16–22, 2026
# For each day: pulls games + final scores, builds 27-feature matrix,
# then saves everything to a multi-sheet Excel file.
# =============================================================================


# =============================================================================
# CELL 1 — Install & Import
# =============================================================================

!pip install -q requests beautifulsoup4 pandas numpy vaderSentiment feedparser lxml openpyxl

import requests
import feedparser
import re
import time
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from datetime import date, timedelta
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from IPython.display import display
from google.colab import drive
drive.mount('/content/drive')

import shutil

analyzer = SentimentIntensityAnalyzer()

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/120.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.9',
}

# Date range: Feb 16 – Feb 22, 2026
START_DATE = date(2026, 2, 16)
END_DATE   = date(2026, 3, 1)
DATE_RANGE = [START_DATE + timedelta(days=i)
              for i in range((END_DATE - START_DATE).days + 1)]

print(f"✅ Setup complete.")
print(f"   Date range: {START_DATE} to {END_DATE} ({len(DATE_RANGE)} days)")

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 6.2 MB/s eta 0:00:00
  Building wheel for sgmllib3k (setup.py) ... done
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Setup complete.
   Date range: 2026-02-16 to 2026-03-01 (14 days)

## Cell 2

In [3]:
# =============================================================================
# CELL 2 — CBS Sports Scraper
# =============================================================================

def get_games_for_date_cbs(game_date):
    date_str = game_date.strftime('%Y%m%d')
    url      = f"https://www.cbssports.com/college-basketball/scoreboard/FBS/{date_str}/"
    games    = []

    try:
        r = requests.get(url, headers=HEADERS, timeout=20)
        r.raise_for_status()
        soup = BeautifulSoup(r.text, 'lxml')

        game_cards = soup.find_all('div', class_='single-score-card')
        print(f"  {date_str}: {len(game_cards)} game cards found")

        for card in game_cards:
            try:
                # ── 1. away/home abbrevs from data-abbrev ─────────────────────
                abbrev   = card.get('data-abbrev', '')
                at_chunk = abbrev.split('_')[-1]
                if '@' not in at_chunk:
                    continue
                away_abbr, home_abbr = at_chunk.split('@', 1)

                # ── 2. game status ────────────────────────────────────────────
                status_div = card.find('div', class_='game-status')
                status_raw = status_div.get_text(strip=True).lower() \
                             if status_div else ''
                is_final   = 'final' in status_raw
                if not is_final:
                    continue

                # ── 3. get all <tr> rows (skip header row with no class) ──────
                # BS sees class='tiedGame' on both rows pre-JS render
                # Row order from data-abbrev is reliable: row 0 = away, row 1 = home
                all_trs = [tr for tr in card.find_all('tr')
                           if tr.get('class') is not None]

                if len(all_trs) < 2:
                    print(f"    ⚠️  Less than 2 data rows in {abbrev}")
                    continue

                away_row = all_trs[0]
                home_row = all_trs[1]

                # ── 4. extract name and score from a row ──────────────────────
                def get_name(row):
                    a = row.find('a', class_='team-name-link')
                    return a.get_text(strip=True) if a else None

                def get_score(row):
                    td = row.find('td', class_='total')
                    if td:
                        val = td.get_text(strip=True)
                        return int(val) if val.isdigit() else None
                    return None

                away_name  = get_name(away_row)
                away_score = get_score(away_row)
                home_name  = get_name(home_row)
                home_score = get_score(home_row)

                if not away_name or not home_name:
                    continue

                # ── 5. determine winner/loser from scores ─────────────────────
                if away_score is not None and home_score is not None:
                    if home_score > away_score:
                        winner_name, winner_score = home_name, home_score
                        loser_name,  loser_score  = away_name, away_score
                        home_team_won = 1
                    elif away_score > home_score:
                        winner_name, winner_score = away_name, away_score
                        loser_name,  loser_score  = home_name, home_score
                        home_team_won = 0
                    else:
                        # Genuine tie — should not happen in college basketball
                        winner_name = winner_score = None
                        loser_name  = loser_score  = None
                        home_team_won = None
                else:
                    winner_name = winner_score = None
                    loser_name  = loser_score  = None
                    home_team_won = None

                games.append({
                    'date':          game_date.strftime('%Y-%m-%d'),
                    'away_name':     away_name,
                    'away_score':    away_score,
                    'home_name':     home_name,
                    'home_score':    home_score,
                    'status':        'Final',
                    'home_team_won': home_team_won,
                    'winner_name':   winner_name,
                    'winner_score':  winner_score,
                    'loser_name':    loser_name,
                    'loser_score':   loser_score,
                })

            except Exception as e:
                print(f"    ⚠️  {abbrev}: {e}")
                continue

    except Exception as e:
        print(f"  ❌ Failed to fetch {date_str}: {e}")

    print(f"  {date_str}: {len(games)} final games parsed")
    return games

## Cell 3

In [4]:
# =============================================================================
# CELL 3 — Feature Extraction (same 27-feature schema as main program)
# =============================================================================

# ── Keyword dictionaries ──────────────────────────────────────────────────────
INJURY_KEYWORDS    = ['injur','hurt','out for','day-to-day','doubtful','questionable',
                      'sidelined','knee','ankle','concussion','surgery','absence',
                      'missed','will not play','won\'t play']
LINEUP_KEYWORDS    = ['starting lineup','starting five','lineup change',
                      'inserted into the starting','moved to the bench','benched',
                      'starter','rotation change','depth chart','replacing','new starter']
WIN_KEYWORDS       = ['win','victory','beat','defeated','upset','dominant','blowout',
                      'rolled','cruised','overcame','rallied','comeback','unbeaten','streak']
LOSS_KEYWORDS      = ['loss','lost','defeated','fell to','blown out','collapse',
                      'losing streak','skid','slide','struggle','winless']
MOMENTUM_KEYWORDS  = ['hot','on fire','rolling','clicking','momentum','confidence',
                      'energized','surging','impressive run','on a roll','winning streak']
SLUMP_KEYWORDS     = ['slump','cold','struggling','disappointing','slow','inconsistent',
                      'frustrating','skidding','dropped','winless','rough patch']
COACHING_KEYWORDS  = ['coach','head coach','staff','scheme','strategy','adjustment',
                      'system','game plan','coaching staff','fired','hired','contract',
                      'press conference']
RANKING_KEYWORDS   = ['ranked','ranking','top 25','ap poll','net ranking','bracketology',
                      'seed','projection','poll','ballot','moved up','dropped','climbed']
FATIGUE_KEYWORDS   = ['back-to-back','travel','tired','rest','fatigue','load management',
                      'minutes','heavy schedule','third game','quick turnaround']
HOME_AWAY_KEYWORDS = ['home court','home crowd','road game','away game',
                      'hostile environment','sold out','neutral site',
                      'home advantage','visiting']


def keyword_score(text, keywords):
    text_lower = text.lower()
    hits = sum(1 for kw in keywords if kw in text_lower)
    return min(hits / max(len(keywords) * 0.15, 1), 1.0)


def count_keyword_hits(texts, keywords):
    if not texts: return 0.0
    hits = sum(1 for t in texts if any(kw in t.lower() for kw in keywords))
    return hits / len(texts)


def mean_vader(texts):
    if not texts: return 0.0
    return float(np.mean([analyzer.polarity_scores(t)['compound'] for t in texts]))


def fetch_google_news_articles(team_name, max_articles=20, top_links=3):
    query    = requests.utils.quote(f"{team_name} mens college basketball NCAAB")
    url      = f"https://news.google.com/rss/search?q={query}&hl=en-US&gl=US&ceid=US:en"
    articles = []
    try:
        feed    = feedparser.parse(url)
        entries = feed.entries[:max_articles]
        for i, entry in enumerate(entries):
            title      = entry.get('title', '')
            source_url = entry.get('link', '')
            full_text  = title
            if i < top_links and source_url:
                try:
                    r = requests.get(source_url, headers=HEADERS,
                                     timeout=10, allow_redirects=True)
                    r.raise_for_status()
                    full_text = f"{title} {r.text}"
                except requests.exceptions.TooManyRedirects:
                    pass
                except requests.exceptions.Timeout:
                    pass
                except Exception:
                    pass
            articles.append({'title': title, 'full_text': full_text,
                              'source_url': source_url, 'source': 'google_news'})
    except Exception:
        pass
    return articles


def fetch_espn_news_articles(team_name, max_articles=15):
    query    = requests.utils.quote(f"{team_name} college basketball")
    url      = (f"https://site.api.espn.com/apis/common/v3/search"
                f"?query={query}&limit={max_articles}&type=article"
                f"&sport=mens-college-basketball")
    articles = []
    try:
        r    = requests.get(url, headers=HEADERS, timeout=12)
        data = r.json()
        for item in data.get('results', [])[:max_articles]:
            title = item.get('headline', item.get('title', ''))
            desc  = item.get('description', item.get('summary', ''))
            articles.append({'title': title, 'full_text': f"{title} {desc}",
                              'source_url': '', 'source': 'espn'})
    except Exception:
        pass
    return articles


def fetch_espn_targeted(team_name, suffix, max_articles=10):
    query    = requests.utils.quote(f"{team_name} {suffix}")
    url      = (f"https://site.api.espn.com/apis/common/v3/search"
                f"?query={query}&limit={max_articles}&type=article"
                f"&sport=mens-college-basketball")
    articles = []
    try:
        r    = requests.get(url, headers=HEADERS, timeout=12)
        data = r.json()
        for item in data.get('results', [])[:max_articles]:
            title = item.get('headline', '')
            desc  = item.get('description', '')
            articles.append({'title': title, 'full_text': f"{title} {desc}",
                              'source_url': '', 'source': 'espn'})
    except Exception:
        pass
    return articles


def extract_team_features(team_name):
    """Extracts 27 named features for a team using news + sentiment analysis."""
    gn_arts     = fetch_google_news_articles(team_name)
    espn_arts   = fetch_espn_news_articles(team_name)
    inj_arts    = fetch_espn_targeted(team_name, 'injury OR injured OR out')
    lineup_arts = fetch_espn_targeted(team_name, 'lineup OR starter OR rotation OR benched')

    all_arts    = gn_arts + espn_arts
    all_texts   = [a['full_text'] for a in all_arts]
    hl_texts    = [a['title']     for a in all_arts]
    gn_texts    = [a['full_text'] for a in gn_arts]
    espn_texts  = [a['full_text'] for a in espn_arts]
    inj_texts   = [a['full_text'] for a in inj_arts]
    ln_texts    = [a['full_text'] for a in lineup_arts]
    total       = len(all_arts)

    all_scores  = ([analyzer.polarity_scores(t)['compound'] for t in all_texts]
                   if all_texts else [0.0])
    recent      = all_texts[-5:] if len(all_texts) >= 5 else all_texts

    star_re     = re.compile(
        r'(star|leading scorer|best player|top player|key player|starting)'
        r'.{0,40}(injur|out|sidelined|miss)', re.IGNORECASE)
    coach_re    = re.compile(
        r'(coach).{0,30}(fired|resign|left|replaced|interim|stepping down)',
        re.IGNORECASE)

    combined_inj = all_texts + inj_texts
    combined_ln  = all_texts + ln_texts

    return {
        'team_name': team_name,
        # [A] Sentiment
        'sent_overall':               round(mean_vader(all_texts), 4),
        'sent_espn':                  round(mean_vader(espn_texts), 4),
        'sent_google':                round(mean_vader(gn_texts), 4),
        'sent_headlines':             round(mean_vader(hl_texts), 4),
        'sent_recent':                round(mean_vader(recent), 4),
        'sent_pct_positive_articles': round(sum(1 for s in all_scores if s >  0.05) / max(total, 1), 4),
        'sent_pct_negative_articles': round(sum(1 for s in all_scores if s < -0.05) / max(total, 1), 4),
        # [B] Injury
        'inj_mention_rate':           round(count_keyword_hits(combined_inj, INJURY_KEYWORDS), 4),
        'inj_severity_score':         round(max((keyword_score(t, INJURY_KEYWORDS) for t in combined_inj), default=0.0), 4),
        'inj_article_count_norm':     round(min(len(inj_arts) / 10.0, 1.0), 4),
        'inj_key_player_flag':        float(any(star_re.search(t) for t in combined_inj)),
        'inj_sentiment':              round(mean_vader(inj_texts), 4),
        # [C] Lineup
        'lineup_change_signal':       round(count_keyword_hits(combined_ln, LINEUP_KEYWORDS), 4),
        'lineup_starter_mention_rate':round(count_keyword_hits(combined_ln, ['starter','starting']), 4),
        'lineup_benched_signal':      round(count_keyword_hits(combined_ln, ['bench','benched','moved to bench']), 4),
        'lineup_roster_instability':  round(min((count_keyword_hits(combined_ln, LINEUP_KEYWORDS) * 0.5 +
                                                 count_keyword_hits(combined_inj, INJURY_KEYWORDS) * 0.5), 1.0), 4),
        'lineup_sentiment':           round(mean_vader(ln_texts), 4),
        # [D] Momentum
        'momentum_win_mention_rate':  round(count_keyword_hits(all_texts, WIN_KEYWORDS), 4),
        'momentum_loss_mention_rate': round(count_keyword_hits(all_texts, LOSS_KEYWORDS), 4),
        'momentum_score':             round(count_keyword_hits(all_texts, MOMENTUM_KEYWORDS), 4),
        'momentum_slump_score':       round(count_keyword_hits(all_texts, SLUMP_KEYWORDS), 4),
        'momentum_net':               round(count_keyword_hits(all_texts, MOMENTUM_KEYWORDS) -
                                            count_keyword_hits(all_texts, SLUMP_KEYWORDS), 4),
        'momentum_win_loss_ratio':    round(count_keyword_hits(all_texts, WIN_KEYWORDS) /
                                            max(count_keyword_hits(all_texts, LOSS_KEYWORDS), 0.01), 4),
        # [E] Context
        'ctx_coaching_mention_rate':  round(count_keyword_hits(all_texts, COACHING_KEYWORDS), 4),
        'ctx_coaching_instability':   float(any(coach_re.search(t) for t in all_texts)),
        'ctx_ranking_mention_rate':   round(count_keyword_hits(all_texts, RANKING_KEYWORDS), 4),
        'ctx_fatigue_signal':         round(count_keyword_hits(all_texts, FATIGUE_KEYWORDS), 4),
        'ctx_home_away_context':      round(count_keyword_hits(all_texts, HOME_AWAY_KEYWORDS), 4),
        # [F] Data quality
        'data_total_articles_norm':   round(min(total / 35.0, 1.0), 4),
        'data_source_diversity':      round(float((len(gn_arts) > 0) + (len(espn_arts) > 0) +
                                                  (len(inj_arts) > 0) + (len(lineup_arts) > 0)) / 4.0, 4),
        'data_confidence':            round((min(total / 35.0, 1.0) * 0.5 +
                                             float((len(gn_arts) > 0) + (len(espn_arts) > 0) +
                                                   (len(inj_arts) > 0) + (len(lineup_arts) > 0)) / 4.0 * 0.5), 4),
    }

## Cell 4

In [5]:
# =============================================================================
# CELL 4 — Main Loop: Iterate Over Each Date
# =============================================================================

all_games_df    = []
processed_teams = {}  # team_name -> feature dict (cache — avoids re-fetching)

print("=" * 65)
print("  NCAAB TRAINING DATA COLLECTION — Feb 16–22, 2026")
print("=" * 65)

for game_date in DATE_RANGE:
    date_str = game_date.strftime('%Y-%m-%d')
    print(f"\n{'─'*65}")
    print(f"  📅 Processing {date_str}")
    print(f"{'─'*65}")

    # ── Step A: Scrape games for this date ────────────────────────────────────
    day_games = get_games_for_date_cbs(game_date)

    if not day_games:
        print(f"  ⚠️  No games found for {date_str}, skipping.")
        continue

    day_games_df = pd.DataFrame(day_games)

    # ── Validate score columns ────────────────────────────────────────────────
    day_games_df['away_score']    = pd.to_numeric(day_games_df['away_score'],    errors='coerce')
    day_games_df['home_score']    = pd.to_numeric(day_games_df['home_score'],    errors='coerce')
    day_games_df['home_team_won'] = pd.to_numeric(day_games_df['home_team_won'], errors='coerce')

    # ── Derive winner/loser columns ───────────────────────────────────────────
    day_games_df['winner_name']  = np.where(day_games_df['home_team_won'] == 1, day_games_df['home_name'], day_games_df['away_name'])
    day_games_df['winner_score'] = np.where(day_games_df['home_team_won'] == 1, day_games_df['home_score'], day_games_df['away_score'])
    day_games_df['loser_name']   = np.where(day_games_df['home_team_won'] == 1, day_games_df['away_name'], day_games_df['home_name'])
    day_games_df['loser_score']  = np.where(day_games_df['home_team_won'] == 1, day_games_df['away_score'], day_games_df['home_score'])

    # ── Cross-check scores ────────────────────────────────────────────────────
    final_games  = day_games_df.dropna(subset=['home_team_won'])
    score_errors = final_games[final_games['winner_score'] <= final_games['loser_score']]
    if not score_errors.empty:
        print(f"  ⚠️  {len(score_errors)} game(s) with score mismatches:")
        for _, row in score_errors.iterrows():
            print(f"      {row['away_name']} {row['away_score']} @ "
                  f"{row['home_name']} {row['home_score']}")

    # ── Display preview ───────────────────────────────────────────────────────
    display_cols = ['date','away_name','away_score','home_name','home_score',
                    'winner_name','winner_score','loser_name','loser_score',
                    'status','home_team_won']
    print(f"\n  Games: {len(day_games_df)} total, {len(final_games)} final")
    #display(day_games_df[display_cols])

    all_games_df.append(day_games_df)

    # ── Step B: Features — use exact names from Step A, use cache ────────────
    # Pull team names directly from the scraped DataFrame rows — no transformation
    teams_today = {}
    for _, row in day_games_df.iterrows():
        home = row['home_name']
        away = row['away_name']
        if pd.notna(home):
            teams_today[home] = home
        if pd.notna(away):
            teams_today[away] = away

    new_teams    = [t for t in teams_today if t not in processed_teams]
    cached_teams = [t for t in teams_today if t in processed_teams]

    print(f"\n  Teams today      : {len(teams_today)}")
    print(f"  ✅ Cached (skip) : {len(cached_teams)}")
    print(f"  🔍 New (fetch)   : {len(new_teams)}")

    if cached_teams:
        print(f"  Reusing cached features for: {', '.join(cached_teams)}")

    for i, team_name in enumerate(new_teams):
        print(f"\n    [{i+1}/{len(new_teams)}] Fetching: {team_name:<40}", end=' ')
        try:
            feats = extract_team_features(team_name)

            # ── Overwrite team_name in feats with the exact name from Step A ──
            # extract_team_features() may internally strip or alter the name;
            # this guarantees the key in processed_teams matches all_games_df exactly
            feats['team_name'] = team_name

            processed_teams[team_name] = feats
            print(f"sent={feats['sent_overall']:+.3f}  "
                  f"momentum={feats['momentum_net']:+.3f}  "
                  f"conf={feats['data_confidence']:.2f}")
        except Exception as e:
            print(f"❌ {e}")
        time.sleep(0.4)

print(f"\n{'='*65}")
print(f"  ✅ Collection complete.")
print(f"     Total games    : {sum(len(d) for d in all_games_df)}")
print(f"     Final games    : {sum(len(d.dropna(subset=['home_team_won'])) for d in all_games_df)}")
print(f"     Unique teams   : {len(processed_teams)}")
print(f"     API calls saved: {sum(len(d) for d in all_games_df) * 2 - len(processed_teams)}")
print(f"{'='*65}")

=================================================================
  NCAAB TRAINING DATA COLLECTION — Feb 16–22, 2026
=================================================================

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-16
─────────────────────────────────────────────────────────────────
  20260216: 24 game cards found
  20260216: 24 final games parsed

  Games: 24 total, 24 final

  Teams today      : 48
  ✅ Cached (skip) : 0
  🔍 New (fetch)   : 48

    [1/48] Fetching: East Texas A&M                           sent=+0.205  momentum=+0.000  conf=0.41

    [2/48] Fetching: SE Louisiana                             sent=+0.225  momentum=+0.000  conf=0.41

    [3/48] Fetching: SC State                                 sent=+0.232  momentum=+0.000  conf=0.41

    [4/48] Fetching: Coppin St.                               sent=+0.198  momentum=+0.000  conf=0.41

    [5/48] Fetching: Old Dominion                             sent=+0.165  momentum=+0.000  conf=0.41

    [6/48] Fetching: Louisiana                                sent=+0.219  momentum=+0.000  conf=0.41

    [7/48] Fetching: Boston U.                                sent=+0.340  momentum=+0.050  conf=0.41

    [8/48] Fetching: Colgate                                  sent=+0.329  momentum=+0.000  conf=0.41

    [9/48] Fetching: Jackson St.                              sent=+0.270  momentum=+0.000  conf=0.41

    [10/48] Fetching: Bethune-Cook.                            sent=+0.252  momentum=+0.000  conf=0.41

    [11/48] Fetching: Duke                                     sent=+0.435  momentum=+0.000  conf=0.41

    [12/48] Fetching: Syracuse                                 sent=+0.296  momentum=+0.000  conf=0.41

    [13/48] Fetching: Prairie View                             sent=+0.337  momentum=+0.000  conf=0.41

    [14/48] Fetching: Grambling St.                            sent=+0.284  momentum=+0.000  conf=0.41

    [15/48] Fetching: Delaware St.                             sent=+0.177  momentum=+0.000  conf=0.41

    [16/48] Fetching: Howard                                   sent=+0.286  momentum=+0.000  conf=0.41

    [17/48] Fetching: NC Central                               sent=+0.237  momentum=+0.000  conf=0.41

    [18/48] Fetching: Morgan St.                               sent=+0.286  momentum=+0.000  conf=0.41

    [19/48] Fetching: Alabama St.                              sent=+0.099  momentum=+0.000  conf=0.41

    [20/48] Fetching: Miss Valley St.                          sent=+0.047  momentum=+0.000  conf=0.41

    [21/48] Fetching: Md.-E. Shore                             sent=+0.173  momentum=+0.000  conf=0.41

    [22/48] Fetching: Norfolk St.                              sent=+0.037  momentum=+0.000  conf=0.41

    [23/48] Fetching: Marshall                                 sent=+0.286  momentum=+0.050  conf=0.41

    [24/48] Fetching: South Alabama                            sent=+0.303  momentum=+0.000  conf=0.41

    [25/48] Fetching: LIU                                      sent=+0.420  momentum=+0.000  conf=0.41

    [26/48] Fetching: Wagner                                   sent=+0.318  momentum=+0.000  conf=0.41

    [27/48] Fetching: UT-Rio Grande Valley                     sent=+0.258  momentum=+0.000  conf=0.41

    [28/48] Fetching: Lamar                                    sent=+0.446  momentum=+0.050  conf=0.41

    [29/48] Fetching: Northwestern St.                         sent=+0.152  momentum=+0.000  conf=0.41

    [30/48] Fetching: McNeese                                  sent=-0.042  momentum=+0.000  conf=0.41

    [31/48] Fetching: Incarnate Word                           sent=+0.000  momentum=+0.000  conf=0.00

    [32/48] Fetching: New Orleans                              sent=+0.110  momentum=+0.000  conf=0.41

    [33/48] Fetching: Tarleton St.                             sent=+0.088  momentum=+0.050  conf=0.41

    [34/48] Fetching: Abilene Chr.                             sent=+0.174  momentum=+0.000  conf=0.41

    [35/48] Fetching: Alabama A&M                              sent=+0.264  momentum=+0.000  conf=0.41

    [36/48] Fetching: Ark.-Pine Bluff                          sent=+0.373  momentum=+0.000  conf=0.41

    [37/48] Fetching: Stony Brook                              sent=+0.224  momentum=+0.000  conf=0.41

    [38/48] Fetching: Drexel                                   sent=+0.515  momentum=+0.000  conf=0.41

    [39/48] Fetching: Alcorn St.                               sent=+0.168  momentum=+0.000  conf=0.41

    [40/48] Fetching: Florida A&M                              sent=+0.487  momentum=+0.000  conf=0.41

    [41/48] Fetching: Houston Chr.                             sent=+0.227  momentum=-0.050  conf=0.41

    [42/48] Fetching: Nicholls                                 sent=+0.310  momentum=+0.000  conf=0.41

    [43/48] Fetching: TX A&M-CC                                sent=+0.369  momentum=+0.000  conf=0.41

    [44/48] Fetching: SF Austin                                sent=+0.177  momentum=+0.000  conf=0.41

    [45/48] Fetching: Texas So.                                sent=+0.178  momentum=+0.000  conf=0.41

    [46/48] Fetching: Southern U.                              sent=+0.071  momentum=+0.000  conf=0.41

    [47/48] Fetching: Iowa St.                                 sent=+0.238  momentum=+0.000  conf=0.41

    [48/48] Fetching: Houston                                  sent=+0.270  momentum=+0.000  conf=0.41

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-17
─────────────────────────────────────────────────────────────────
  20260217: 30 game cards found
  20260217: 30 final games parsed

  Games: 30 total, 30 final

  Teams today      : 60
  ✅ Cached (skip) : 0
  🔍 New (fetch)   : 60

    [1/60] Fetching: Florida St.                              sent=+0.277  momentum=+0.000  conf=0.41

    [2/60] Fetching: Boston College                           sent=+0.190  momentum=+0.050  conf=0.41

    [3/60] Fetching: Charleston So.                           sent=+0.227  momentum=+0.000  conf=0.41

    [4/60] Fetching: Gardner-Webb                             sent=+0.439  momentum=+0.050  conf=0.41

    [5/60] Fetching: E. Michigan                              sent=+0.043  momentum=+0.000  conf=0.41

    [6/60] Fetching: C. Michigan                              sent=+0.242  momentum=+0.000  conf=0.41

    [7/60] Fetching: Purdue                                   sent=+0.292  momentum=+0.050  conf=0.41

    [8/60] Fetching: Michigan                                 sent=+0.240  momentum=+0.000  conf=0.41

    [9/60] Fetching: Buffalo                                  sent=+0.273  momentum=+0.000  conf=0.41

    [10/60] Fetching: N. Illinois                              sent=+0.386  momentum=+0.050  conf=0.41

    [11/60] Fetching: Xavier                                   sent=+0.069  momentum=+0.000  conf=0.41

    [12/60] Fetching: Villanova                                sent=+0.196  momentum=+0.000  conf=0.41

    [13/60] Fetching: W. Michigan                              sent=+0.204  momentum=+0.050  conf=0.41

    [14/60] Fetching: Akron                                    sent=+0.364  momentum=+0.050  conf=0.41

    [15/60] Fetching: Ohio                                     sent=+0.221  momentum=+0.050  conf=0.41

    [16/60] Fetching: Ball St.                                 sent=+0.180  momentum=+0.000  conf=0.41

    [17/60] Fetching: Bowling Green                            sent=+0.379  momentum=+0.000  conf=0.41

    [18/60] Fetching: Kent St.                                 sent=+0.222  momentum=+0.000  conf=0.41

    [19/60] Fetching: SMU                                      sent=+0.299  momentum=+0.000  conf=0.41

    [20/60] Fetching: Louisville                               sent=+0.223  momentum=+0.050  conf=0.41

    [21/60] Fetching: Massachusetts                            sent=+0.428  momentum=+0.000  conf=0.41

    [22/60] Fetching: Miami (Ohio)                             sent=+0.121  momentum=+0.050  conf=0.41

    [23/60] Fetching: Florida                                  sent=+0.266  momentum=+0.000  conf=0.41

    [24/60] Fetching: S. Carolina                              sent=+0.352  momentum=+0.050  conf=0.41

    [25/60] Fetching: Rhode Island                             sent=+0.153  momentum=+0.000  conf=0.41

    [26/60] Fetching: Saint Louis                              sent=+0.279  momentum=+0.000  conf=0.41

    [27/60] Fetching: UCF                                      sent=+0.185  momentum=+0.000  conf=0.41

    [28/60] Fetching: TCU                                      sent=+0.165  momentum=+0.000  conf=0.41

    [29/60] Fetching: NC State                                 sent=+0.167  momentum=+0.000  conf=0.41

    [30/60] Fetching: N. Carolina                              sent=+0.265  momentum=+0.100  conf=0.41

    [31/60] Fetching: VCU                                      sent=+0.064  momentum=+0.000  conf=0.41

    [32/60] Fetching: George Wash.                             sent=+0.299  momentum=+0.000  conf=0.41

    [33/60] Fetching: Miami                                    sent=+0.149  momentum=+0.000  conf=0.41

    [34/60] Fetching: Va. Tech                                 sent=+0.225  momentum=+0.000  conf=0.41

    [35/60] Fetching: Wyoming                                  sent=+0.406  momentum=+0.000  conf=0.41

    [36/60] Fetching: Fresno St.                               sent=+0.099  momentum=+0.000  conf=0.41

    [37/60] Fetching: Michigan St.                             sent=+0.263  momentum=+0.000  conf=0.41

    [38/60] Fetching: UCLA                                     sent=+0.328  momentum=+0.000  conf=0.41

    [39/60] Fetching: Ohio St.                                 sent=+0.164  momentum=+0.100  conf=0.41

    [40/60] Fetching: Wisconsin                                sent=+0.143  momentum=+0.000  conf=0.41

    [41/60] Fetching: UT Martin                                sent=+0.222  momentum=+0.050  conf=0.41

    [42/60] Fetching: SE Missouri St.                          sent=+0.209  momentum=+0.000  conf=0.41

    [43/60] Fetching: New Mexico                               sent=+0.254  momentum=+0.050  conf=0.41

    [44/60] Fetching: Air Force                                sent=+0.312  momentum=+0.000  conf=0.41

    [45/60] Fetching: Kansas St.                               sent=+0.070  momentum=+0.050  conf=0.41

    [46/60] Fetching: Baylor                                   sent=+0.072  momentum=+0.000  conf=0.41

    [47/60] Fetching: Texas                                    sent=+0.212  momentum=+0.000  conf=0.41

    [48/60] Fetching: LSU                                      sent=+0.192  momentum=+0.000  conf=0.41

    [49/60] Fetching: Iowa                                     sent=+0.212  momentum=+0.000  conf=0.41

    [50/60] Fetching: Nebraska                                 sent=+0.197  momentum=+0.000  conf=0.41

    [51/60] Fetching: Kentucky                                 sent=+0.364  momentum=+0.050  conf=0.41

    [52/60] Fetching: Georgia                                  sent=+0.079  momentum=+0.000  conf=0.41

    [53/60] Fetching: San Diego St.                            sent=+0.186  momentum=+0.000  conf=0.41

    [54/60] Fetching: Grand Canyon                             sent=+0.397  momentum=+0.000  conf=0.41

    [55/60] Fetching: San Jose St.                             sent=+0.344  momentum=+0.000  conf=0.41

    [56/60] Fetching: Nevada                                   sent=+0.417  momentum=+0.000  conf=0.41

    [57/60] Fetching: Oregon                                   sent=+0.119  momentum=+0.000  conf=0.41

    [58/60] Fetching: Minnesota                                sent=+0.086  momentum=+0.000  conf=0.41

    [59/60] Fetching: Arizona St.                              sent=+0.038  momentum=+0.000  conf=0.41

    [60/60] Fetching: Texas Tech                               sent=+0.181  momentum=+0.000  conf=0.41

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-18
─────────────────────────────────────────────────────────────────
  20260218: 59 game cards found
  20260218: 59 final games parsed

  Games: 59 total, 59 final

  Teams today      : 118
  ✅ Cached (skip) : 2
  🔍 New (fetch)   : 116
  Reusing cached features for: SC State, NC Central

    [1/116] Fetching: Holy Cross                               sent=+0.439  momentum=+0.000  conf=0.41

    [2/116] Fetching: Lafayette                                sent=+0.307  momentum=+0.000  conf=0.41

    [3/116] Fetching: Penn St.                                 sent=+0.175  momentum=+0.000  conf=0.41

    [4/116] Fetching: Rutgers                                  sent=+0.155  momentum=+0.000  conf=0.41

    [5/116] Fetching: Wofford                                  sent=+0.408  momentum=+0.000  conf=0.41

    [6/116] Fetching: VMI                                      sent=+0.251  momentum=+0.000  conf=0.41

    [7/116] Fetching: Georgetown                               sent=+0.192  momentum=-0.050  conf=0.41

    [8/116] Fetching: Butler                                   sent=+0.228  momentum=+0.000  conf=0.41

    [9/116] Fetching: Youngstown St.                           sent=+0.166  momentum=+0.000  conf=0.41

    [10/116] Fetching: Clev. St.                                sent=+0.148  momentum=+0.000  conf=0.41

    [11/116] Fetching: Furman                                   sent=+0.429  momentum=+0.000  conf=0.41

    [12/116] Fetching: ETSU                                     sent=+0.209  momentum=+0.000  conf=0.41

    [13/116] Fetching: Bucknell                                 sent=+0.386  momentum=+0.000  conf=0.41

    [14/116] Fetching: American                                 sent=+0.228  momentum=+0.000  conf=0.41

    [15/116] Fetching: Alabama                                  sent=+0.245  momentum=+0.050  conf=0.41

    [16/116] Fetching: Arkansas                                 sent=+0.155  momentum=+0.000  conf=0.41

    [17/116] Fetching: Loyola-Md.                               sent=+0.425  momentum=+0.050  conf=0.41

    [18/116] Fetching: Army                                     sent=+0.277  momentum=+0.000  conf=0.41

    [19/116] Fetching: Valparaiso                               sent=+0.468  momentum=+0.000  conf=0.41

    [20/116] Fetching: Bradley                                  sent=+0.286  momentum=+0.000  conf=0.41

    [21/116] Fetching: Wake Forest                              sent=+0.094  momentum=+0.050  conf=0.41

    [22/116] Fetching: Clemson                                  sent=+0.018  momentum=+0.000  conf=0.41

    [23/116] Fetching: UConn                                    sent=+0.292  momentum=+0.000  conf=0.41

    [24/116] Fetching: Creighton                                sent=+0.246  momentum=+0.000  conf=0.41

    [25/116] Fetching: George Mason                             sent=+0.209  momentum=+0.000  conf=0.41

    [26/116] Fetching: Dayton                                   sent=+0.198  momentum=+0.000  conf=0.41

    [27/116] Fetching: N. Kentucky                              sent=+0.365  momentum=+0.050  conf=0.41

    [28/116] Fetching: PFW                                      sent=+0.157  momentum=+0.000  conf=0.41

    [29/116] Fetching: C. Carolina                              sent=+0.306  momentum=+0.050  conf=0.41

    [30/116] Fetching: James Madison                            sent=+0.138  momentum=+0.050  conf=0.41

    [31/116] Fetching: FGCU                                     sent=+0.123  momentum=+0.000  conf=0.41

    [32/116] Fetching: Jacksonville                             sent=+0.304  momentum=+0.000  conf=0.41

    [33/116] Fetching: Navy                                     sent=+0.206  momentum=+0.150  conf=0.41

    [34/116] Fetching: Lehigh                                   sent=+0.413  momentum=+0.000  conf=0.41

    [35/116] Fetching: Fordham                                  sent=+0.175  momentum=+0.000  conf=0.41

    [36/116] Fetching: Loyola Chi.                              sent=+0.162  momentum=+0.000  conf=0.41

    [37/116] Fetching: Duquesne                                 sent=+0.476  momentum=+0.000  conf=0.41

    [38/116] Fetching: La Salle                                 sent=+0.194  momentum=+0.000  conf=0.41

    [39/116] Fetching: Texas A&M                                sent=+0.143  momentum=+0.000  conf=0.41

    [40/116] Fetching: Ole Miss                                 sent=+0.240  momentum=+0.000  conf=0.41

    [41/116] Fetching: W. Carolina                              sent=+0.155  momentum=+0.000  conf=0.41

    [42/116] Fetching: UNCG                                     sent=+0.473  momentum=+0.000  conf=0.41

    [43/116] Fetching: Indiana St.                              sent=+0.150  momentum=+0.000  conf=0.41

    [44/116] Fetching: N. Iowa                                  sent=+0.214  momentum=+0.000  conf=0.41

    [45/116] Fetching: Tennessee                                sent=+0.135  momentum=+0.000  conf=0.41

    [46/116] Fetching: Oklahoma                                 sent=+0.180  momentum=+0.000  conf=0.41

    [47/116] Fetching: N. Alabama                               sent=+0.261  momentum=+0.000  conf=0.41

    [48/116] Fetching: Queens                                   sent=+0.206  momentum=+0.050  conf=0.41

    [49/116] Fetching: Davidson                                 sent=+0.257  momentum=+0.000  conf=0.41

    [50/116] Fetching: Richmond                                 sent=+0.316  momentum=+0.050  conf=0.41

    [51/116] Fetching: St. Bona.                                sent=+0.336  momentum=+0.050  conf=0.41

    [52/116] Fetching: Saint Joseph's                           sent=+0.161  momentum=+0.000  conf=0.41

    [53/116] Fetching: Temple                                   sent=+0.167  momentum=+0.050  conf=0.41

    [54/116] Fetching: UAB                                      sent=+0.338  momentum=+0.000  conf=0.41

    [55/116] Fetching: E. Kentucky                              sent=+0.175  momentum=+0.000  conf=0.41

    [56/116] Fetching: W. Georgia                               sent=+0.177  momentum=+0.000  conf=0.41

    [57/116] Fetching: East Carolina                            sent=+0.184  momentum=+0.000  conf=0.41

    [58/116] Fetching: Wichita St.                              sent=+0.200  momentum=+0.000  conf=0.41

    [59/116] Fetching: Delaware                                 sent=+0.260  momentum=+0.000  conf=0.41

    [60/116] Fetching: W. Kentucky                              sent=+0.174  momentum=+0.050  conf=0.41

    [61/116] Fetching: La. Tech                                 sent=+0.408  momentum=+0.000  conf=0.41

    [62/116] Fetching: Jax. State                               sent=+0.378  momentum=+0.000  conf=0.41

    [63/116] Fetching: Bellarmine                               sent=+0.333  momentum=+0.000  conf=0.41

    [64/116] Fetching: Lipscomb                                 sent=+0.489  momentum=+0.050  conf=0.41

    [65/116] Fetching: Sam Houston                              sent=+0.422  momentum=+0.000  conf=0.41

    [66/116] Fetching: Middle Tenn.                             sent=+0.197  momentum=+0.050  conf=0.41

    [67/116] Fetching: Drake                                    sent=+0.055  momentum=+0.000  conf=0.41

    [68/116] Fetching: S. Illinois                              sent=+0.373  momentum=+0.000  conf=0.41

    [69/116] Fetching: UL-Monroe                                sent=+0.162  momentum=+0.000  conf=0.41

    [70/116] Fetching: Troy                                     sent=+0.179  momentum=+0.000  conf=0.41

    [71/116] Fetching: Tulsa                                    sent=+0.194  momentum=+0.000  conf=0.41

    [72/116] Fetching: Charlotte                                sent=+0.195  momentum=+0.000  conf=0.41


## Cell 4B

In [6]:
# =============================================================================
# CELL 4b — Re-scrape Games Only (Step A only, Step B skipped)
# Run this cell to refresh game scores without re-fetching team features
# =============================================================================

all_games_df = []

print("=" * 65)
print("  NCAAB GAME SCRAPE ONLY — Feb 16–22, 2026")
print("  (Step B / feature extraction skipped)")
print("=" * 65)

for game_date in DATE_RANGE:
    date_str = game_date.strftime('%Y-%m-%d')
    print(f"\n{'─'*65}")
    print(f"  📅 Processing {date_str}")
    print(f"{'─'*65}")

    # ── Step A: Scrape games for this date ────────────────────────────────────
    day_games = get_games_for_date_cbs(game_date)

    if not day_games:
        print(f"  ⚠️  No games found for {date_str}, skipping.")
        continue

    day_games_df = pd.DataFrame(day_games)

    # ── Validate score columns ────────────────────────────────────────────────
    for col in ['winner_score', 'loser_score', 'score_diff']:
        if col in day_games_df.columns:
            day_games_df[col] = pd.to_numeric(day_games_df[col], errors='coerce')

    # ── Cross-check: winner score must always be >= loser score ──────────────
    final_games  = day_games_df.dropna(subset=['winner_name'])
    score_errors = final_games[
        final_games['winner_score'] <= final_games['loser_score']
    ]
    if not score_errors.empty:
        print(f"  ⚠️  {len(score_errors)} game(s) with score mismatches:")
        for _, row in score_errors.iterrows():
            print(f"      {row['winner_name']} {row['winner_score']} vs "
                  f"{row['loser_name']} {row['loser_score']}")

    # ── Display preview ───────────────────────────────────────────────────────
    print(f"\n  Games: {len(day_games_df)} total, {len(final_games)} final")
    display(day_games_df)

    all_games_df.append(day_games_df)

# ── Assemble master games DataFrame ──────────────────────────────────────────
master_games_df = pd.concat(all_games_df, ignore_index=True)

print(f"\n{'='*65}")
print(f"  ✅ Game scrape complete.")
print(f"     Total games  : {len(master_games_df)}")
print(f"     Final games  : {len(master_games_df.dropna(subset=['winner_name']))}")
print(f"     processed_teams cache untouched: {len(processed_teams)} teams")
print(f"{'='*65}")

=================================================================
  NCAAB GAME SCRAPE ONLY — Feb 16–22, 2026
  (Step B / feature extraction skipped)
=================================================================

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-16
─────────────────────────────────────────────────────────────────
  20260216: 24 game cards found
  20260216: 24 final games parsed

  Games: 24 total, 24 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-16,SE Louisiana,53,East Texas A&M,70,Final,1,East Texas A&M,70,SE Louisiana,53
1,2026-02-16,Coppin St.,59,SC State,57,Final,0,Coppin St.,59,SC State,57
2,2026-02-16,Louisiana,72,Old Dominion,83,Final,1,Old Dominion,83,Louisiana,72
3,2026-02-16,Colgate,58,Boston U.,85,Final,1,Boston U.,85,Colgate,58
4,2026-02-16,Bethune-Cook.,86,Jackson St.,91,Final,1,Jackson St.,91,Bethune-Cook.,86
5,2026-02-16,Syracuse,64,Duke,101,Final,1,Duke,101,Syracuse,64
6,2026-02-16,Grambling St.,63,Prairie View,68,Final,1,Prairie View,68,Grambling St.,63
7,2026-02-16,Howard,91,Delaware St.,59,Final,0,Howard,91,Delaware St.,59
8,2026-02-16,Morgan St.,76,NC Central,80,Final,1,NC Central,80,Morgan St.,76
9,2026-02-16,Miss Valley St.,55,Alabama St.,92,Final,1,Alabama St.,92,Miss Valley St.,55
10,2026-02-16,Norfolk St.,70,Md.-E. Shore,66,Final,0,Norfolk St.,70,Md.-E. Shore,66
11,2026-02-16,South Alabama,80,Marshall,84,Final,1,Marshall,84,South Alabama,80
12,2026-02-16,Wagner,65,LIU,83,Final,1,LIU,83,Wagner,65
13,2026-02-16,Lamar,65,UT-Rio Grande Valley,70,Final,1,UT-Rio Grande Valley,70,Lamar,65
14,2026-02-16,McNeese,75,Northwestern St.,64,Final,0,McNeese,75,Northwestern St.,64
15,2026-02-16,New Orleans,78,Incarnate Word,64,Final,0,New Orleans,78,Incarnate Word,64
16,2026-02-16,Abilene Chr.,62,Tarleton St.,65,Final,1,Tarleton St.,65,Abilene Chr.,62
17,2026-02-16,Ark.-Pine Bluff,70,Alabama A&M,82,Final,1,Alabama A&M,82,Ark.-Pine Bluff,70
18,2026-02-16,Drexel,69,Stony Brook,72,Final,1,Stony Brook,72,Drexel,69
19,2026-02-16,Florida A&M,86,Alcorn St.,78,Final,0,Florida A&M,86,Alcorn St.,78
20,2026-02-16,Nicholls,68,Houston Chr.,72,Final,1,Houston Chr.,72,Nicholls,68
21,2026-02-16,SF Austin,78,TX A&M-CC,68,Final,0,SF Austin,78,TX A&M-CC,68
22,2026-02-16,Southern U.,73,Texas So.,74,Final,1,Texas So.,74,Southern U.,73
23,2026-02-16,Houston,67,Iowa St.,70,Final,1,Iowa St.,70,Houston,67

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-17
─────────────────────────────────────────────────────────────────
  20260217: 30 game cards found
  20260217: 30 final games parsed

  Games: 30 total, 30 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-17,Boston College,72,Florida St.,80,Final,1,Florida St.,80,Boston College,72
1,2026-02-17,Gardner-Webb,66,Charleston So.,75,Final,1,Charleston So.,75,Gardner-Webb,66
2,2026-02-17,C. Michigan,54,E. Michigan,66,Final,1,E. Michigan,66,C. Michigan,54
3,2026-02-17,Michigan,91,Purdue,80,Final,0,Michigan,91,Purdue,80
4,2026-02-17,N. Illinois,72,Buffalo,70,Final,0,N. Illinois,72,Buffalo,70
5,2026-02-17,Villanova,92,Xavier,89,Final,0,Villanova,92,Xavier,89
6,2026-02-17,Akron,90,W. Michigan,73,Final,0,Akron,90,W. Michigan,73
7,2026-02-17,Ball St.,57,Ohio,69,Final,1,Ohio,69,Ball St.,57
8,2026-02-17,Kent St.,78,Bowling Green,71,Final,0,Kent St.,78,Bowling Green,71
9,2026-02-17,Louisville,85,SMU,95,Final,1,SMU,95,Louisville,85
10,2026-02-17,Miami (Ohio),86,Massachusetts,77,Final,0,Miami (Ohio),86,Massachusetts,77
11,2026-02-17,S. Carolina,62,Florida,76,Final,1,Florida,76,S. Carolina,62
12,2026-02-17,Saint Louis,76,Rhode Island,81,Final,1,Rhode Island,81,Saint Louis,76
13,2026-02-17,TCU,71,UCF,82,Final,1,UCF,82,TCU,71
14,2026-02-17,N. Carolina,58,NC State,82,Final,1,NC State,82,N. Carolina,58
15,2026-02-17,George Wash.,75,VCU,89,Final,1,VCU,89,George Wash.,75
16,2026-02-17,Va. Tech,66,Miami,67,Final,1,Miami,67,Va. Tech,66
17,2026-02-17,Fresno St.,82,Wyoming,92,Final,1,Wyoming,92,Fresno St.,82
18,2026-02-17,UCLA,59,Michigan St.,82,Final,1,Michigan St.,82,UCLA,59
19,2026-02-17,Wisconsin,69,Ohio St.,86,Final,1,Ohio St.,86,Wisconsin,69
20,2026-02-17,SE Missouri St.,56,UT Martin,53,Final,0,SE Missouri St.,56,UT Martin,53
21,2026-02-17,Air Force,61,New Mexico,98,Final,1,New Mexico,98,Air Force,61
22,2026-02-17,Baylor,74,Kansas St.,90,Final,1,Kansas St.,90,Baylor,74
23,2026-02-17,LSU,85,Texas,88,Final,1,Texas,88,LSU,85
24,2026-02-17,Nebraska,52,Iowa,57,Final,1,Iowa,57,Nebraska,52
25,2026-02-17,Georgia,86,Kentucky,78,Final,0,Georgia,86,Kentucky,78
26,2026-02-17,Grand Canyon,73,San Diego St.,63,Final,0,Grand Canyon,73,San Diego St.,63
27,2026-02-17,Nevada,71,San Jose St.,87,Final,1,San Jose St.,87,Nevada,71
28,2026-02-17,Minnesota,61,Oregon,44,Final,0,Minnesota,61,Oregon,44
29,2026-02-17,Texas Tech,67,Arizona St.,72,Final,1,Arizona St.,72,Texas Tech,67

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-18
─────────────────────────────────────────────────────────────────
  20260218: 59 game cards found
  20260218: 59 final games parsed

  Games: 59 total, 59 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-18,Lafayette,86,Holy Cross,83,Final,0,Lafayette,86,Holy Cross,83
1,2026-02-18,Rutgers,85,Penn St.,72,Final,0,Rutgers,85,Penn St.,72
2,2026-02-18,VMI,76,Wofford,82,Final,1,Wofford,82,VMI,76
3,2026-02-18,Butler,93,Georgetown,89,Final,0,Butler,93,Georgetown,89
4,2026-02-18,Clev. St.,82,Youngstown St.,106,Final,1,Youngstown St.,106,Clev. St.,82
5,2026-02-18,ETSU,78,Furman,69,Final,0,ETSU,78,Furman,69
6,2026-02-18,American,75,Bucknell,57,Final,0,American,75,Bucknell,57
7,2026-02-18,Arkansas,115,Alabama,117,Final,1,Alabama,117,Arkansas,115
8,2026-02-18,Army,87,Loyola-Md.,77,Final,0,Army,87,Loyola-Md.,77
9,2026-02-18,Bradley,72,Valparaiso,79,Final,1,Valparaiso,79,Bradley,72
10,2026-02-18,Clemson,77,Wake Forest,85,Final,1,Wake Forest,85,Clemson,77
11,2026-02-18,Creighton,91,UConn,84,Final,0,Creighton,91,UConn,84
12,2026-02-18,Dayton,82,George Mason,67,Final,0,Dayton,82,George Mason,67
13,2026-02-18,PFW,71,N. Kentucky,87,Final,1,N. Kentucky,87,PFW,71
14,2026-02-18,James Madison,67,C. Carolina,65,Final,0,James Madison,67,C. Carolina,65
15,2026-02-18,Jacksonville,84,FGCU,86,Final,1,FGCU,86,Jacksonville,84
16,2026-02-18,Lehigh,49,Navy,72,Final,1,Navy,72,Lehigh,49
17,2026-02-18,Loyola Chi.,59,Fordham,62,Final,1,Fordham,62,Loyola Chi.,59
18,2026-02-18,La Salle,61,Duquesne,62,Final,1,Duquesne,62,La Salle,61
19,2026-02-18,Ole Miss,77,Texas A&M,80,Final,1,Texas A&M,80,Ole Miss,77
20,2026-02-18,UNCG,77,W. Carolina,91,Final,1,W. Carolina,91,UNCG,77
21,2026-02-18,N. Iowa,81,Indiana St.,60,Final,0,N. Iowa,81,Indiana St.,60
22,2026-02-18,Oklahoma,66,Tennessee,89,Final,1,Tennessee,89,Oklahoma,66
23,2026-02-18,Queens,85,N. Alabama,78,Final,0,Queens,85,N. Alabama,78
24,2026-02-18,Richmond,63,Davidson,65,Final,1,Davidson,65,Richmond,63
25,2026-02-18,Saint Joseph's,71,St. Bona.,65,Final,0,Saint Joseph's,71,St. Bona.,65
26,2026-02-18,UAB,76,Temple,71,Final,0,UAB,76,Temple,71
27,2026-02-18,W. Georgia,80,E. Kentucky,81,Final,1,E. Kentucky,81,W. Georgia,80
28,2026-02-18,Wichita St.,92,East Carolina,89,Final,0,Wichita St.,92,East Carolina,89
29,2026-02-18,W. Kentucky,88,Delaware,87,Final,0,W. Kentucky,88,Delaware,87
30,2026-02-18,Jax. State,71,La. Tech,77,Final,1,La. Tech,77,Jax. State,71
31,2026-02-18,Lipscomb,75,Bellarmine,72,Final,0,Lipscomb,75,Bellarmine,72
32,2026-02-18,Middle Tenn.,70,Sam Houston,78,Final,1,Sam Houston,78,Middle Tenn.,70
33,2026-02-18,S. Illinois,66,Drake,61,Final,0,S. Illinois,66,Drake,61
34,2026-02-18,Troy,77,UL-Monroe,76,Final,0,Troy,77,UL-Monroe,76
35,2026-02-18,Charlotte,74,Tulsa,79,Final,1,Tulsa,79,Charlotte,74
36,2026-02-18,DePaul,69,Seton Hall,57,Final,0,DePaul,69,Seton Hall,57
37,2026-02-18,FAU,60,UTSA,52,Final,0,FAU,60,UTSA,52
38,2026-02-18,UIC,84,Evansville,46,Final,0,UIC,84,Evansville,46
39,2026-02-18,Kennesaw St.,91,Missouri St.,87,Final,0,Kennesaw St.,91,Missouri St.,87
40,2026-02-18,Maryland,74,Northwestern,78,Final,1,Northwestern,78,Maryland,74
41,2026-02-18,NC Central,72,SC State,85,Final,1,SC State,85,NC Central,72
42,2026-02-18,N. Dakota St.,74,S. Dak. St.,66,Final,0,N. Dakota St.,74,S. Dak. St.,66
43,2026-02-18,Oral Roberts,71,Omaha,80,Final,1,Omaha,80,Oral Roberts,71
44,2026-02-18,Utah,61,West Virginia,56,Final,0,Utah,61,West Virginia,56
45,2026-02-18,Auburn,85,Miss. St.,91,Final,1,Miss. St.,91,Auburn,85
46,2026-02-18,BYU,68,Arizona,75,Final,1,Arizona,75,BYU,68
47,2026-02-18,Kansas,81,Okla. St.,69,Final,0,Kansas,81,Okla. St.,69
48,2026-02-18,Saint Mary's,72,Seattle,70,Final,0,Saint Mary's,72,Seattle,70
49,2026-02-18,Murray St.,61,Illinois St.,78,Final,1,Illinois St.,78,Murray St.,61
50,2026-02-18,St. John's,76,Marquette,70,Final,0,St. John's,76,Marquette,70
51,2026-02-18,Virginia,94,Ga. Tech,68,Final,0,Virginia,94,Ga. Tech,68
52,2026-02-18,Vanderbilt,80,Missouri,81,Final,1,Missouri,81,Vanderbilt,80
53,2026-02-18,Pacific,70,Wash. St.,87,Final,1,Wash. St.,87,Pacific,70
54,2026-02-18,Illinois,101,USC,65,Final,0,Illinois,101,USC,65
55,2026-02-18,Pepperdine,95,Portland,87,Final,0,Pepperdine,95,Portland,87
56,2026-02-18,Boise St.,56,Utah St.,75,Final,1,Utah St.,75,Boise St.,56
57,2026-02-18,Colo. St.,91,UNLV,86,Final,0,Colo. St.,91,UNLV,86
58,2026-02-18,Gonzaga,80,San Fran.,59,Final,0,Gonzaga,80,San Fran.,59

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-19
─────────────────────────────────────────────────────────────────
  20260219: 52 game cards found
  20260219: 52 final games parsed

  Games: 52 total, 52 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-19,Binghamton,79,Bryant,67,Final,0,Binghamton,79,Bryant,67
1,2026-02-19,FIU,89,Liberty,90,Final,1,Liberty,90,FIU,89
2,2026-02-19,New Hamp.,56,UMass Lowell,78,Final,1,UMass Lowell,78,New Hamp.,56
3,2026-02-19,Vermont,62,UMBC,75,Final,1,UMBC,75,Vermont,62
4,2026-02-19,Marshall,94,App. St.,93,Final,0,Marshall,94,App. St.,93
5,2026-02-19,SC Upstate,64,Winthrop,68,Final,1,Winthrop,68,SC Upstate,64
6,2026-02-19,UAlbany,81,N.J. Tech,63,Final,0,UAlbany,81,N.J. Tech,63
7,2026-02-19,Charleston,74,NC A&T,61,Final,0,Charleston,74,NC A&T,61
8,2026-02-19,Chattanooga,94,Mercer,90,Final,0,Chattanooga,94,Mercer,90
9,2026-02-19,Drexel,70,Northeastern,61,Final,0,Drexel,70,Northeastern,61
10,2026-02-19,FDU,60,Chicago St.,59,Final,0,FDU,60,Chicago St.,59
11,2026-02-19,Gardner-Webb,70,Radford,82,Final,1,Radford,82,Gardner-Webb,70
12,2026-02-19,IUI,73,Wright St.,85,Final,1,Wright St.,85,IUI,73
13,2026-02-19,Le Moyne,77,CCSU,78,Final,1,CCSU,78,Le Moyne,77
14,2026-02-19,LIU,91,Saint Francis,89,Final,0,LIU,91,Saint Francis,89
15,2026-02-19,Longwood,65,Presbyterian,72,Final,1,Presbyterian,72,Longwood,65
16,2026-02-19,Memphis,66,South Florida,87,Final,1,South Florida,87,Memphis,66
17,2026-02-19,Monmouth,69,UNCW,79,Final,1,UNCW,79,Monmouth,69
18,2026-02-19,UNC-Ash.,48,High Point,74,Final,1,High Point,74,UNC-Ash.,48
19,2026-02-19,Austin Peay,77,North Florida,76,Final,0,Austin Peay,77,North Florida,76
20,2026-02-19,Samford,78,The Citadel,75,Final,0,Samford,78,The Citadel,75
21,2026-02-19,Stonehill,51,New Haven,64,Final,1,New Haven,64,Stonehill,51
22,2026-02-19,Wagner,83,Mercyhurst,80,Final,0,Wagner,83,Mercyhurst,80
23,2026-02-19,William & Mary,83,Campbell,84,Final,1,Campbell,84,William & Mary,83
24,2026-02-19,Alabama St.,71,Bethune-Cook.,82,Final,1,Bethune-Cook.,82,Alabama St.,71
25,2026-02-19,Arkansas St.,79,Louisiana,62,Final,0,Arkansas St.,79,Louisiana,62
26,2026-02-19,Cal Baptist,46,Utah Valley,65,Final,1,Utah Valley,65,Cal Baptist,46
27,2026-02-19,Cent. Arkansas,88,Stetson,76,Final,0,Cent. Arkansas,88,Stetson,76
28,2026-02-19,Ga. Southern,64,Georgia St.,66,Final,1,Georgia St.,66,Ga. Southern,64
29,2026-02-19,Hampton,43,Hofstra,79,Final,1,Hofstra,79,Hampton,43
30,2026-02-19,So. Utah,74,Tarleton St.,78,Final,1,Tarleton St.,78,So. Utah,74
31,2026-02-19,Texas St.,90,South Alabama,82,Final,0,Texas St.,90,South Alabama,82
32,2026-02-19,Kansas City,70,North Dakota,85,Final,1,North Dakota,85,Kansas City,70
33,2026-02-19,Utah Tech,50,UT Arlington,63,Final,1,UT Arlington,63,Utah Tech,50
34,2026-02-19,Lindenwood,80,Tennessee St.,89,Final,1,Tennessee St.,89,Lindenwood,80
35,2026-02-19,Morehead St.,73,E. Illinois,70,Final,0,Morehead St.,73,E. Illinois,70
36,2026-02-19,So. Indiana,77,W. Illinois,70,Final,0,So. Indiana,77,W. Illinois,70
37,2026-02-19,UT Martin,65,Little Rock,67,Final,1,Little Rock,67,UT Martin,65
38,2026-02-19,Prairie View,72,Miss Valley St.,62,Final,0,Prairie View,72,Miss Valley St.,62
39,2026-02-19,SIUE,52,Tenn. Tech,62,Final,1,Tenn. Tech,62,SIUE,52
40,2026-02-19,CSNorthridge,85,UCSB,83,Final,0,CSNorthridge,85,UCSB,83
41,2026-02-19,Idaho,67,Portland St.,77,Final,1,Portland St.,77,Idaho,67
42,2026-02-19,Montana,69,Idaho St.,73,Final,1,Idaho St.,73,Montana,69
43,2026-02-19,Montana St.,79,Weber St.,82,Final,1,Weber St.,82,Montana St.,79
44,2026-02-19,South Dakota,70,Denver,90,Final,1,Denver,90,South Dakota,70
45,2026-02-19,Tulane,77,North Texas,71,Final,0,Tulane,77,North Texas,71
46,2026-02-19,Alabama A&M,63,Florida A&M,61,Final,0,Alabama A&M,63,Florida A&M,61
47,2026-02-19,Texas So.,83,Ark.-Pine Bluff,64,Final,0,Texas So.,83,Ark.-Pine Bluff,64
48,2026-02-19,Cal-Baker.,65,UC Riverside,93,Final,1,UC Riverside,93,Cal-Baker.,65
49,2026-02-19,E. Washington,102,Sacramento St.,94,Final,0,E. Washington,102,Sacramento St.,94
50,2026-02-19,UC Davis,92,CS Fullerton,93,Final,1,CS Fullerton,93,UC Davis,92
51,2026-02-19,UC Irvine,69,LBSU,58,Final,0,UC Irvine,69,LBSU,58

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-20
─────────────────────────────────────────────────────────────────
  20260220: 14 game cards found
  20260220: 14 final games parsed

  Games: 14 total, 14 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-20,Cal Poly,86,Hawaii,75,Final,0,Cal Poly,86,Hawaii,75
1,2026-02-20,Akron,78,Ball St.,65,Final,0,Akron,78,Ball St.,65
2,2026-02-20,Canisius,72,Rider,66,Final,0,Canisius,72,Rider,66
3,2026-02-20,Marist,84,Manhattan,70,Final,0,Marist,84,Manhattan,70
4,2026-02-20,Milwaukee,86,Detroit,91,Final,1,Detroit,91,Milwaukee,86
5,2026-02-20,Niagara,63,Mt St Mary's,76,Final,1,Mt St Mary's,76,Niagara,63
6,2026-02-20,Princeton,71,Brown,80,Final,1,Brown,80,Princeton,71
7,2026-02-20,Sacred Heart,68,Fairfield,78,Final,1,Fairfield,78,Sacred Heart,68
8,2026-02-20,Saint Peter's,64,Iona,72,Final,1,Iona,72,Saint Peter's,64
9,2026-02-20,VCU,75,Saint Louis,88,Final,1,Saint Louis,88,VCU,75
10,2026-02-20,Green Bay,73,Oakland,68,Final,0,Green Bay,73,Oakland,68
11,2026-02-20,Indiana,64,Purdue,93,Final,1,Purdue,93,Indiana,64
12,2026-02-20,Siena,72,Merrimack,79,Final,1,Merrimack,79,Siena,72
13,2026-02-20,Bowling Green,77,Miami (Ohio),91,Final,1,Miami (Ohio),91,Bowling Green,77

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-21
─────────────────────────────────────────────────────────────────
  20260221: 148 game cards found
  20260221: 148 final games parsed

  Games: 148 total, 148 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-21,Creighton,52,St. John's,81,Final,1,St. John's,81,Creighton,52
1,2026-02-21,East Carolina,56,Charlotte,68,Final,1,Charlotte,68,East Carolina,56
2,2026-02-21,Florida,94,Ole Miss,75,Final,0,Florida,94,Ole Miss,75
3,2026-02-21,Florida St.,70,Clemson,65,Final,0,Florida St.,70,Clemson,65
4,2026-02-21,Loyola Chi.,61,Saint Joseph's,75,Final,1,Saint Joseph's,75,Loyola Chi.,61
...,...,...,...,...,...,...,...,...,...,...,...
143,2026-02-21,Portland,59,Seattle,71,Final,1,Seattle,71,Portland,59
144,2026-02-21,Santa Clara,94,San Fran.,73,Final,0,Santa Clara,94,San Fran.,73
145,2026-02-21,UCSB,75,Hawaii,78,Final,1,Hawaii,78,UCSB,75
146,2026-02-21,Utah St.,77,Nevada,80,Final,1,Nevada,80,Utah St.,77
147,2026-02-21,Iowa St.,69,BYU,79,Final,1,BYU,79,Iowa St.,69

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-22
─────────────────────────────────────────────────────────────────
  20260222: 21 game cards found
  20260222: 21 final games parsed

  Games: 21 total, 21 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-22,American,75,Lafayette,61,Final,0,American,75,Lafayette,61
1,2026-02-22,Boston U.,67,Lehigh,70,Final,1,Lehigh,70,Boston U.,67
2,2026-02-22,Holy Cross,72,Bucknell,63,Final,0,Holy Cross,72,Bucknell,63
3,2026-02-22,Niagara,62,Rider,67,Final,1,Rider,67,Niagara,62
4,2026-02-22,UAB,78,Memphis,67,Final,0,UAB,78,Memphis,67
5,2026-02-22,Iona,86,Merrimack,88,Final,1,Merrimack,88,Iona,86
6,2026-02-22,Ohio St.,60,Michigan St.,66,Final,1,Michigan St.,66,Ohio St.,60
7,2026-02-22,Sacred Heart,63,Marist,65,Final,1,Marist,65,Sacred Heart,63
8,2026-02-22,Green Bay,70,Detroit,74,Final,1,Detroit,74,Green Bay,70
9,2026-02-22,Canisius,47,Mt St Mary's,68,Final,1,Mt St Mary's,68,Canisius,47
10,2026-02-22,Fairfield,85,Quinnipiac,79,Final,0,Fairfield,85,Quinnipiac,79
11,2026-02-22,PFW,92,Clev. St.,86,Final,0,PFW,92,Clev. St.,86
12,2026-02-22,N. Kentucky,58,Youngstown St.,64,Final,1,Youngstown St.,64,N. Kentucky,58
13,2026-02-22,Rice,75,Tulane,81,Final,1,Tulane,81,Rice,75
14,2026-02-22,Robert Morris,81,Wright St.,68,Final,0,Robert Morris,81,Wright St.,68
15,2026-02-22,Saint Peter's,63,Siena,72,Final,1,Siena,72,Saint Peter's,63
16,2026-02-22,Towson,62,Drexel,68,Final,1,Drexel,68,Towson,62
17,2026-02-22,Milwaukee,70,Oakland,81,Final,1,Oakland,81,Milwaukee,70
18,2026-02-22,FAU,72,North Texas,73,Final,1,North Texas,73,FAU,72
19,2026-02-22,Iowa,71,Wisconsin,84,Final,1,Wisconsin,84,Iowa,71
20,2026-02-22,UTSA,74,Tulsa,100,Final,1,Tulsa,100,UTSA,74

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-23
─────────────────────────────────────────────────────────────────
  20260223: 9 game cards found
  20260223: 9 final games parsed

  Games: 9 total, 9 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-23,Louisville,74,N. Carolina,77,Final,1,N. Carolina,77,Louisville,74
1,2026-02-23,Nicholls,53,Lamar,52,Final,0,Nicholls,53,Lamar,52
2,2026-02-23,TX A&M-CC,73,SE Louisiana,68,Final,0,TX A&M-CC,73,SE Louisiana,68
3,2026-02-23,Houston Chr.,69,East Texas A&M,68,Final,0,Houston Chr.,69,East Texas A&M,68
4,2026-02-23,New Orleans,77,SF Austin,73,Final,0,New Orleans,77,SF Austin,73
5,2026-02-23,UT-Rio Grande Valley,68,McNeese,75,Final,1,McNeese,75,UT-Rio Grande Valley,68
6,2026-02-23,Incarnate Word,49,Northwestern St.,54,Final,1,Northwestern St.,54,Incarnate Word,49
7,2026-02-23,Houston,56,Kansas,69,Final,1,Kansas,69,Houston,56
8,2026-02-23,Miss Valley St.,62,Grambling St.,83,Final,1,Grambling St.,83,Miss Valley St.,62

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-24
─────────────────────────────────────────────────────────────────
  20260224: 36 game cards found
  20260224: 36 final games parsed

  Games: 36 total, 36 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-24,Saint Francis,73,New Haven,67,Final,0,Saint Francis,73,New Haven,67
1,2026-02-24,George Wash.,104,La Salle,77,Final,0,George Wash.,104,La Salle,77
2,2026-02-24,Miami (Ohio),74,E. Michigan,64,Final,0,Miami (Ohio),74,E. Michigan,64
3,2026-02-24,Washington,79,Rutgers,72,Final,0,Washington,79,Rutgers,72
4,2026-02-24,Buffalo,85,Akron,99,Final,1,Akron,99,Buffalo,85
5,2026-02-24,Cincinnati,68,Texas Tech,80,Final,1,Texas Tech,80,Cincinnati,68
6,2026-02-24,C. Michigan,81,Kent St.,83,Final,1,Kent St.,83,C. Michigan,81
7,2026-02-24,Duke,100,Notre Dame,56,Final,0,Duke,100,Notre Dame,56
8,2026-02-24,Marquette,76,Georgetown,60,Final,0,Marquette,76,Georgetown,60
9,2026-02-24,NC State,61,Virginia,90,Final,1,Virginia,90,NC State,61
10,2026-02-24,N. Illinois,69,Toledo,79,Final,1,Toledo,79,N. Illinois,69
11,2026-02-24,Northwestern,72,Indiana,68,Final,0,Northwestern,72,Indiana,68
12,2026-02-24,Old Dominion,88,Marshall,97,Final,1,Marshall,97,Old Dominion,88
13,2026-02-24,Saint Louis,62,Dayton,77,Final,1,Dayton,77,Saint Louis,62
14,2026-02-24,Kentucky,72,S. Carolina,63,Final,0,Kentucky,72,S. Carolina,63
15,2026-02-24,Louisiana,59,Troy,78,Final,1,Troy,78,Louisiana,59
16,2026-02-24,Massachusetts,73,Ball St.,74,Final,1,Ball St.,74,Massachusetts,73
17,2026-02-24,W. Michigan,88,Bowling Green,79,Final,0,W. Michigan,88,Bowling Green,79
18,2026-02-24,West Virginia,84,Okla. St.,91,Final,1,Okla. St.,91,West Virginia,84
19,2026-02-24,C. Carolina,76,Georgia St.,71,Final,0,C. Carolina,76,Georgia St.,71
20,2026-02-24,So. Indiana,63,Morehead St.,64,Final,1,Morehead St.,64,So. Indiana,63
21,2026-02-24,Bradley,86,UIC,93,Final,1,UIC,93,Bradley,86
22,2026-02-24,Minnesota,67,Michigan,77,Final,1,Michigan,77,Minnesota,67
23,2026-02-24,So. Miss,84,Arkansas St.,89,Final,1,Arkansas St.,89,So. Miss,84
24,2026-02-24,Arizona,87,Baylor,80,Final,0,Arizona,87,Baylor,80
25,2026-02-24,Arizona St.,78,TCU,90,Final,1,TCU,90,Arizona St.,78
26,2026-02-24,Auburn,79,Oklahoma,91,Final,1,Oklahoma,91,Auburn,79
27,2026-02-24,Fresno St.,70,Colo. St.,74,Final,1,Colo. St.,74,Fresno St.,70
28,2026-02-24,Iowa St.,75,Utah,59,Final,0,Iowa St.,75,Utah,59
29,2026-02-24,Miami,83,Florida St.,73,Final,0,Miami,83,Florida St.,73
30,2026-02-24,San Jose St.,86,Air Force,80,Final,0,San Jose St.,86,Air Force,80
31,2026-02-24,Tennessee,69,Missouri,73,Final,1,Missouri,73,Tennessee,69
32,2026-02-24,Wyoming,62,Boise St.,72,Final,1,Boise St.,72,Wyoming,62
33,2026-02-24,New Mexico,60,Nevada,67,Final,1,Nevada,67,New Mexico,60
34,2026-02-24,UCF,97,BYU,84,Final,0,UCF,97,BYU,84
35,2026-02-24,USC,62,UCLA,81,Final,1,UCLA,81,USC,62

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-25
─────────────────────────────────────────────────────────────────
  20260225: 54 game cards found
  20260225: 54 final games parsed

  Games: 54 total, 54 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-25,Bucknell,75,Army,73,Final,0,Bucknell,75,Army,73
1,2026-02-25,The Citadel,51,Furman,72,Final,1,Furman,72,The Citadel,51
2,2026-02-25,Morgan St.,90,SC State,83,Final,0,Morgan St.,90,SC State,83
3,2026-02-25,Wake Forest,67,Boston College,68,Final,1,Boston College,68,Wake Forest,67
4,2026-02-25,Oakland,86,IUI,74,Final,0,Oakland,86,IUI,74
5,2026-02-25,Butler,73,Villanova,82,Final,1,Villanova,82,Butler,73
6,2026-02-25,Davidson,67,Duquesne,56,Final,0,Davidson,67,Duquesne,56
7,2026-02-25,Detroit,62,Robert Morris,73,Final,1,Robert Morris,73,Detroit,62
8,2026-02-25,Florida,84,Texas,71,Final,0,Florida,84,Texas,71
9,2026-02-25,George Mason,63,Saint Joseph's,81,Final,1,Saint Joseph's,81,George Mason,63
10,2026-02-25,Holy Cross,63,Boston U.,78,Final,1,Boston U.,78,Holy Cross,63
11,2026-02-25,Illinois St.,71,N. Iowa,69,Final,0,Illinois St.,71,N. Iowa,69
12,2026-02-25,Lafayette,70,Colgate,69,Final,0,Lafayette,70,Colgate,69
13,2026-02-25,Lehigh,78,American,73,Final,0,Lehigh,78,American,73
14,2026-02-25,Lipscomb,77,W. Georgia,84,Final,1,W. Georgia,84,Lipscomb,77
15,2026-02-25,Maryland,61,Nebraska,74,Final,1,Nebraska,74,Maryland,61
16,2026-02-25,Mercer,74,W. Carolina,78,Final,1,W. Carolina,78,Mercer,74
17,2026-02-25,Navy,78,Loyola-Md.,51,Final,0,Navy,78,Loyola-Md.,51
18,2026-02-25,N. Kentucky,81,Clev. St.,70,Final,0,N. Kentucky,81,Clev. St.,70
19,2026-02-25,North Texas,79,Charlotte,80,Final,1,Charlotte,80,North Texas,79
20,2026-02-25,Omaha,72,South Dakota,89,Final,1,South Dakota,89,Omaha,72
21,2026-02-25,Queens,96,E. Kentucky,79,Final,0,Queens,96,E. Kentucky,79
22,2026-02-25,St. John's,40,UConn,72,Final,1,UConn,72,St. John's,40
23,2026-02-25,Georgia,80,Vanderbilt,88,Final,1,Vanderbilt,88,Georgia,80
24,2026-02-25,Wofford,72,ETSU,69,Final,0,Wofford,72,ETSU,69
25,2026-02-25,Wright St.,74,PFW,70,Final,0,Wright St.,74,PFW,70
26,2026-02-25,Evansville,64,Belmont,98,Final,1,Belmont,98,Evansville,64
27,2026-02-25,Tulsa,90,Tulane,56,Final,0,Tulsa,90,Tulane,56
28,2026-02-25,Xavier,84,Providence,94,Final,1,Providence,94,Xavier,84
29,2026-02-25,Drake,71,Valparaiso,74,Final,1,Valparaiso,74,Drake,71
30,2026-02-25,East Carolina,82,UTSA,81,Final,0,East Carolina,82,UTSA,81
31,2026-02-25,Ga. Southern,66,James Madison,82,Final,1,James Madison,82,Ga. Southern,66
32,2026-02-25,Indiana St.,55,S. Illinois,66,Final,1,S. Illinois,66,Indiana St.,55
33,2026-02-25,Pittsburgh,67,Stanford,75,Final,1,Stanford,75,Pittsburgh,67
34,2026-02-25,South Florida,75,Rice,56,Final,0,South Florida,75,Rice,56
35,2026-02-25,Youngstown St.,65,Milwaukee,78,Final,1,Milwaukee,78,Youngstown St.,65
36,2026-02-25,Cent. Arkansas,93,Austin Peay,88,Final,0,Cent. Arkansas,93,Austin Peay,88
37,2026-02-25,UL-Monroe,54,South Alabama,89,Final,1,South Alabama,89,UL-Monroe,54
38,2026-02-25,DePaul,72,Creighton,71,Final,0,DePaul,72,Creighton,71
39,2026-02-25,Kansas St.,70,Colorado,79,Final,1,Colorado,79,Kansas St.,70
40,2026-02-25,LSU,106,Ole Miss,99,Final,0,LSU,106,Ole Miss,99
41,2026-02-25,Miss. St.,75,Alabama,100,Final,1,Alabama,100,Miss. St.,75
42,2026-02-25,Ohio St.,57,Iowa,74,Final,1,Iowa,74,Ohio St.,57
43,2026-02-25,Portland,48,Gonzaga,89,Final,1,Gonzaga,89,Portland,48
44,2026-02-25,Seattle,87,Pepperdine,80,Final,0,Seattle,87,Pepperdine,80
45,2026-02-25,Texas A&M,84,Arkansas,99,Final,1,Arkansas,99,Texas A&M,84
46,2026-02-25,UNLV,67,Grand Canyon,80,Final,1,Grand Canyon,80,UNLV,67
47,2026-02-25,Bellarmine,68,N. Alabama,73,Final,1,N. Alabama,73,Bellarmine,68
48,2026-02-25,SMU,69,California,73,Final,1,California,73,SMU,69
49,2026-02-25,San Diego,82,Oregon St.,92,Final,1,Oregon St.,92,San Diego,82
50,2026-02-25,Santa Clara,67,Saint Mary's,86,Final,1,Saint Mary's,86,Santa Clara,67
51,2026-02-25,Utah St.,72,San Diego St.,89,Final,1,San Diego St.,89,Utah St.,72
52,2026-02-25,Wash. St.,66,LMU,67,Final,1,LMU,67,Wash. St.,66
53,2026-02-25,Wisconsin,71,Oregon,85,Final,1,Oregon,85,Wisconsin,71

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-26
─────────────────────────────────────────────────────────────────
  20260226: 57 game cards found
  20260226: 57 final games parsed

  Games: 57 total, 57 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-26,Charleston,85,Hampton,71,Final,0,Charleston,85,Hampton,71
1,2026-02-26,Rhode Island,76,St. Bona.,94,Final,1,St. Bona.,94,Rhode Island,76
2,2026-02-26,Bryant,58,UMBC,70,Final,1,UMBC,70,Bryant,58
3,2026-02-26,New Hamp.,63,Binghamton,65,Final,1,Binghamton,65,New Hamp.,63
4,2026-02-26,Bethune-Cook.,76,Grambling St.,71,Final,0,Bethune-Cook.,76,Grambling St.,71
5,2026-02-26,Maine,70,UAlbany,59,Final,0,Maine,70,UAlbany,59
6,2026-02-26,Campbell,60,Drexel,65,Final,1,Drexel,65,Campbell,60
7,2026-02-26,Chicago St.,56,LIU,73,Final,1,LIU,73,Chicago St.,56
8,2026-02-26,Delaware,70,Jax. State,80,Final,1,Jax. State,80,Delaware,70
9,2026-02-26,Elon,56,Towson,58,Final,1,Towson,58,Elon,56
10,2026-02-26,FDU,59,Le Moyne,76,Final,1,Le Moyne,76,FDU,59
11,2026-02-26,FGCU,70,North Florida,76,Final,1,North Florida,76,FGCU,70
12,2026-02-26,High Point,79,Presbyterian,73,Final,0,High Point,79,Presbyterian,73
13,2026-02-26,Liberty,65,Kennesaw St.,74,Final,1,Kennesaw St.,74,Liberty,65
14,2026-02-26,UMass Lowell,64,Vermont,66,Final,1,Vermont,66,UMass Lowell,64
15,2026-02-26,Mercyhurst,78,CCSU,80,Final,1,CCSU,80,Mercyhurst,78
16,2026-02-26,UNC-Ash.,77,Gardner-Webb,71,Final,0,UNC-Ash.,77,Gardner-Webb,71
17,2026-02-26,NC A&T,65,UNCW,88,Final,1,UNCW,88,NC A&T,65
18,2026-02-26,UNCG,85,Chattanooga,80,Final,0,UNCG,85,Chattanooga,80
19,2026-02-26,Northeastern,77,William & Mary,84,Final,1,William & Mary,84,Northeastern,77
20,2026-02-26,New Haven,62,Wagner,65,Final,1,Wagner,65,New Haven,62
21,2026-02-26,Saint Francis,77,Stonehill,103,Final,1,Stonehill,103,Saint Francis,77
22,2026-02-26,Stetson,85,Jacksonville,89,Final,1,Jacksonville,89,Stetson,85
23,2026-02-26,Stony Brook,69,Monmouth,82,Final,1,Monmouth,82,Stony Brook,69
24,2026-02-26,Temple,73,FAU,77,Final,1,FAU,77,Temple,73
25,2026-02-26,SC Upstate,59,Radford,71,Final,1,Radford,71,SC Upstate,59
26,2026-02-26,Winthrop,84,Charleston So.,86,Final,1,Charleston So.,86,Winthrop,84
27,2026-02-26,Missouri St.,70,La. Tech,72,Final,1,La. Tech,72,Missouri St.,70
28,2026-02-26,N. Mex. St.,70,W. Kentucky,93,Final,1,W. Kentucky,93,N. Mex. St.,70
29,2026-02-26,UTEP,67,Middle Tenn.,77,Final,1,Middle Tenn.,77,UTEP,67
30,2026-02-26,Denver,80,Oral Roberts,102,Final,1,Oral Roberts,102,Denver,80
31,2026-02-26,Michigan St.,76,Purdue,74,Final,0,Michigan St.,76,Purdue,74
32,2026-02-26,S. Dak. St.,73,Kansas City,59,Final,0,S. Dak. St.,73,Kansas City,59
33,2026-02-26,Tarleton St.,72,Utah Valley,79,Final,1,Utah Valley,79,Tarleton St.,72
34,2026-02-26,VMI,61,Samford,80,Final,1,Samford,80,VMI,61
35,2026-02-26,Alcorn St.,87,Texas So.,92,Final,1,Texas So.,92,Alcorn St.,87
36,2026-02-26,E. Illinois,71,Lindenwood,67,Final,0,E. Illinois,71,Lindenwood,67
37,2026-02-26,Florida A&M,82,Southern U.,71,Final,0,Florida A&M,82,Southern U.,71
38,2026-02-26,Tennessee St.,79,SE Missouri St.,71,Final,0,Tennessee St.,79,SE Missouri St.,71
39,2026-02-26,Tenn. Tech,49,UT Martin,64,Final,1,UT Martin,64,Tenn. Tech,49
40,2026-02-26,W. Illinois,47,SIUE,67,Final,1,SIUE,67,W. Illinois,47
41,2026-02-26,Morehead St.,76,Little Rock,70,Final,0,Morehead St.,76,Little Rock,70
42,2026-02-26,Abilene Chr.,81,Utah Tech,85,Final,1,Utah Tech,85,Abilene Chr.,81
43,2026-02-26,FIU,67,Sam Houston,100,Final,1,Sam Houston,100,FIU,67
44,2026-02-26,Hawaii,77,UC Davis,73,Final,0,Hawaii,77,UC Davis,73
45,2026-02-26,N. Arizona,58,Idaho,78,Final,1,Idaho,78,N. Arizona,58
46,2026-02-26,N. Colorado,72,E. Washington,82,Final,1,E. Washington,82,N. Colorado,72
47,2026-02-26,N. Dakota St.,62,St. Thomas (MN),84,Final,1,St. Thomas (MN),84,N. Dakota St.,62
48,2026-02-26,Portland St.,69,Montana St.,84,Final,1,Montana St.,84,Portland St.,69
49,2026-02-26,Sacramento St.,73,Montana,81,Final,1,Montana,81,Sacramento St.,73
50,2026-02-26,UC Riverside,59,UCSB,70,Final,1,UCSB,70,UC Riverside,59
51,2026-02-26,Wichita St.,88,Memphis,82,Final,0,Wichita St.,88,Memphis,82
52,2026-02-26,Jackson St.,76,Prairie View,85,Final,1,Prairie View,85,Jackson St.,76
53,2026-02-26,Cal-Baker.,72,UC San Diego,84,Final,1,UC San Diego,84,Cal-Baker.,72
54,2026-02-26,LBSU,92,Cal Poly,102,Final,1,Cal Poly,102,LBSU,92
55,2026-02-26,UT Arlington,56,Cal Baptist,68,Final,1,Cal Baptist,68,UT Arlington,56
56,2026-02-26,UC Irvine,68,CSNorthridge,67,Final,0,UC Irvine,68,CSNorthridge,67

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-27
─────────────────────────────────────────────────────────────────
  20260227: 21 game cards found
  20260227: 21 final games parsed

  Games: 21 total, 21 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-27,Miami (Ohio),69,W. Michigan,67,Final,0,Miami (Ohio),69,W. Michigan,67
1,2026-02-27,Yale,69,Cornell,72,Final,1,Cornell,72,Yale,69
2,2026-02-27,Quinnipiac,76,Niagara,78,Final,1,Niagara,78,Quinnipiac,76
3,2026-02-27,Brown,62,Columbia,80,Final,1,Columbia,80,Brown,62
4,2026-02-27,Dartmouth,71,Penn,80,Final,1,Penn,80,Dartmouth,71
5,2026-02-27,Dayton,68,George Wash.,66,Final,0,Dayton,68,George Wash.,66
6,2026-02-27,Harvard,58,Princeton,56,Final,0,Harvard,58,Princeton,56
7,2026-02-27,UL-Monroe,65,Troy,80,Final,1,Troy,80,UL-Monroe,65
8,2026-02-27,Manhattan,65,Saint Peter's,75,Final,1,Saint Peter's,75,Manhattan,65
9,2026-02-27,Merrimack,62,Canisius,67,Final,1,Canisius,67,Merrimack,62
10,2026-02-27,Mt St Mary's,69,Sacred Heart,77,Final,1,Sacred Heart,77,Mt St Mary's,69
11,2026-02-27,Rider,58,Iona,80,Final,1,Iona,80,Rider,58
12,2026-02-27,Siena,58,Fairfield,72,Final,1,Fairfield,72,Siena,58
13,2026-02-27,Old Dominion,81,Georgia St.,73,Final,0,Old Dominion,81,Georgia St.,73
14,2026-02-27,Akron,92,Kent St.,70,Final,0,Akron,92,Kent St.,70
15,2026-02-27,App. St.,57,Texas St.,60,Final,1,Texas St.,60,App. St.,57
16,2026-02-27,C. Carolina,69,James Madison,68,Final,0,C. Carolina,69,James Madison,68
17,2026-02-27,Michigan,84,Illinois,70,Final,0,Michigan,84,Illinois,70
18,2026-02-27,Louisiana,58,Arkansas St.,81,Final,1,Arkansas St.,81,Louisiana,58
19,2026-02-27,So. Miss,68,South Alabama,55,Final,0,So. Miss,68,South Alabama,55
20,2026-02-27,Ga. Southern,99,Marshall,82,Final,0,Ga. Southern,99,Marshall,82

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-02-28
─────────────────────────────────────────────────────────────────
  20260228: 143 game cards found
  20260228: 143 final games parsed

  Games: 143 total, 143 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-02-28,Boston U.,68,American,65,Final,0,Boston U.,68,American,65
1,2026-02-28,Colorado,62,Houston,102,Final,1,Houston,102,Colorado,62
2,2026-02-28,Florida St.,80,Ga. Tech,71,Final,0,Florida St.,80,Ga. Tech,71
3,2026-02-28,Iowa,69,Penn St.,71,Final,1,Penn St.,71,Iowa,69
4,2026-02-28,Loyola-Md.,76,Holy Cross,62,Final,0,Loyola-Md.,76,Holy Cross,62
...,...,...,...,...,...,...,...,...,...,...,...
138,2026-02-28,Cal Poly,64,UC San Diego,80,Final,1,UC San Diego,80,Cal Poly,64
139,2026-02-28,Grand Canyon,69,Utah St.,74,Final,1,Utah St.,74,Grand Canyon,69
140,2026-02-28,Nevada,83,UNLV,85,Final,1,UNLV,85,Nevada,83
141,2026-02-28,Gonzaga,59,Saint Mary's,70,Final,1,Saint Mary's,70,Gonzaga,59
142,2026-02-28,UCSB,60,UC Irvine,64,Final,1,UC Irvine,64,UCSB,60

─────────────────────────────────────────────────────────────────
  📅 Processing 2026-03-01
─────────────────────────────────────────────────────────────────
  20260301: 23 game cards found
  20260301: 23 final games parsed

  Games: 23 total, 23 final

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score
0,2026-03-01,La Salle,64,Davidson,71,Final,1,Davidson,71,La Salle,64
1,2026-03-01,North Texas,62,UAB,58,Final,0,North Texas,62,UAB,58
2,2026-03-01,Rutgers,69,Maryland,65,Final,0,Rutgers,69,Maryland,65
3,2026-03-01,Tulane,62,South Florida,90,Final,1,South Florida,90,Tulane,62
4,2026-03-01,UIC,63,Indiana St.,79,Final,1,Indiana St.,79,UIC,63
5,2026-03-01,Quinnipiac,67,Canisius,63,Final,0,Quinnipiac,67,Canisius,63
6,2026-03-01,Purdue,74,Ohio St.,82,Final,1,Ohio St.,82,Purdue,74
7,2026-03-01,Charlotte,76,FAU,77,Final,1,FAU,77,Charlotte,76
8,2026-03-01,Iona,69,Manhattan,65,Final,0,Iona,69,Manhattan,65
9,2026-03-01,Memphis,68,East Carolina,84,Final,1,East Carolina,84,Memphis,68
10,2026-03-01,Merrimack,73,Niagara,66,Final,0,Merrimack,73,Niagara,66
11,2026-03-01,Mt St Mary's,69,Fairfield,47,Final,0,Mt St Mary's,69,Fairfield,47
12,2026-03-01,Murray St.,78,Bradley,87,Final,1,Bradley,87,Murray St.,78
13,2026-03-01,Rice,80,Temple,74,Final,0,Rice,80,Temple,74
14,2026-03-01,Rider,61,Siena,76,Final,1,Siena,76,Rider,61
15,2026-03-01,Saint Peter's,63,Marist,56,Final,0,Saint Peter's,63,Marist,56
16,2026-03-01,N. Iowa,75,Drake,53,Final,0,N. Iowa,75,Drake,53
17,2026-03-01,Michigan St.,77,Indiana,64,Final,0,Michigan St.,77,Indiana,64
18,2026-03-01,DePaul,62,Marquette,51,Final,0,DePaul,62,Marquette,51
19,2026-03-01,S. Illinois,81,Evansville,67,Final,0,S. Illinois,81,Evansville,67
20,2026-03-01,Belmont,74,Illinois St.,81,Final,1,Illinois St.,81,Belmont,74
21,2026-03-01,Charleston,79,UNCW,76,Final,0,Charleston,79,UNCW,76
22,2026-03-01,Wichita St.,84,UTSA,67,Final,0,Wichita St.,84,UTSA,67

=================================================================
  ✅ Game scrape complete.
     Total games  : 691
     Final games  : 691
     processed_teams cache untouched: 365 teams
=================================================================

## Cell 5

In [7]:
# =============================================================================
# CELL 5 — Assemble Final DataFrames
# =============================================================================

# ── Master games table ────────────────────────────────────────────────────────
master_games_df = pd.concat(all_games_df, ignore_index=True)

# ── Master features table ─────────────────────────────────────────────────────
master_features_df = pd.DataFrame(list(processed_teams.values()))

META_COLS    = ['team_name', 'date']
numeric_cols = [c for c in master_features_df.columns if c not in META_COLS]
for col in numeric_cols:
    master_features_df[col] = pd.to_numeric(master_features_df[col],
                                             errors='coerce').fillna(0.0)

# ── Training table: one row per game with both teams' features joined ─────────
# Join home team features
home_feats = master_features_df.add_prefix('home_').rename(
    columns={'home_team_name': 'home_name'})
away_feats = master_features_df.add_prefix('away_').rename(
    columns={'away_team_name': 'away_name'})

training_df = master_games_df.merge(home_feats, on='home_name', how='left')
training_df = training_df.merge(away_feats,     on='away_name', how='left')

# Drop rows with no outcome (non-final games)
training_df = training_df.dropna(subset=['home_team_won']).reset_index(drop=True)
training_df['home_team_won'] = training_df['home_team_won'].astype(int)

print(f"✅ DataFrames assembled.")
print(f"   master_games_df   : {master_games_df.shape}")
print(f"   master_features_df: {master_features_df.shape}")
print(f"   training_df        : {training_df.shape}  ← use this for ML training")

✅ DataFrames assembled.
   master_games_df   : (691, 11)
   master_features_df: (365, 32)
   training_df        : (691, 73)  ← use this for ML training

## Cell 6

In [8]:
# =============================================================================
# CELL 6 — Save to CSV
# =============================================================================

import os

OUTPUT_PATH = '/content/drive/MyDrive/Colab Notebooks'

# ── Mount Google Drive ────────────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# ── Assemble master games DataFrame ──────────────────────────────────────────
master_games_df = pd.concat(all_games_df, ignore_index=True)

# ── Assemble master features DataFrame from cache ────────────────────────────
master_features_df = pd.DataFrame(list(processed_teams.values()))
META_COLS    = ['team_name']
numeric_cols = [c for c in master_features_df.columns if c not in META_COLS]
for col in numeric_cols:
    master_features_df[col] = pd.to_numeric(master_features_df[col], errors='coerce').fillna(0.0)

# ── Save ──────────────────────────────────────────────────────────────────────
games_path    = os.path.join(OUTPUT_PATH, 'ncaab_games_2.csv')
features_path = os.path.join(OUTPUT_PATH, 'ncaab_team_features_2.csv')

master_games_df.to_csv(games_path,    index=False)
master_features_df.to_csv(features_path, index=False)

print(f"✅ Saved:")
print(f"   Games CSV    → {games_path}    ({master_games_df.shape[0]} rows × {master_games_df.shape[1]} cols)")
print(f"   Features CSV → {features_path} ({master_features_df.shape[0]} rows × {master_features_df.shape[1]} cols)")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Saved:
   Games CSV    → /content/drive/MyDrive/Colab Notebooks/ncaab_games_2.csv    (691 rows × 11 cols)
   Features CSV → /content/drive/MyDrive/Colab Notebooks/ncaab_team_features_2.csv (365 rows × 32 cols)

In [9]:
master_games_df.shape

(691, 11)

In [10]:
# =============================================================================
# CELL 5 — Assemble Final DataFrames
# =============================================================================

master_games_df = pd.concat(all_games_df, ignore_index=True)

# ── Force numeric on score columns ───────────────────────────────────────────
for col in ['away_score', 'home_score', 'winner_score', 'loser_score']:
    if col in master_games_df.columns:
        master_games_df[col] = pd.to_numeric(master_games_df[col], errors='coerce')

# ── score_diff = home_score minus away_score ──────────────────────────────────
master_games_df['score_diff'] = master_games_df['home_score'] - master_games_df['away_score']

# ── Summary ───────────────────────────────────────────────────────────────────
final_games = master_games_df.dropna(subset=['winner_name'])

print(f"✅ master_games_df assembled.")
print(f"   Total rows        : {len(master_games_df)}")
print(f"   Final games       : {len(final_games)}")
print(f"   Score diff range  : {final_games['score_diff'].min():.0f} "
      f"to {final_games['score_diff'].max():.0f} pts")
print(f"   Home win rate     : {(final_games['home_team_won'] == 1).mean():.1%}")
print(f"\n   Sample:")
display(master_games_df.head(10))


# =============================================================================
# CELL 6 — Save Games CSV to Google Drive
# =============================================================================

import os
from google.colab import drive

drive.mount('/content/drive')

OUTPUT_PATH = '/content/drive/MyDrive/Colab Notebooks'
games_path  = os.path.join(OUTPUT_PATH, 'ncaab_games_2.csv')

master_games_df.to_csv(games_path, index=False)

print(f"✅ Saved:")
print(f"   Games CSV → {games_path}")
print(f"              {len(master_games_df)} rows × {master_games_df.shape[1]} cols")
print(f"\n   Columns saved:")
for col in master_games_df.columns:
    non_null = master_games_df[col].notna().sum()
    print(f"     • {col:<25} ({non_null} non-null / {len(master_games_df)} rows)")

✅ master_games_df assembled.
   Total rows        : 691
   Final games       : 691
   Score diff range  : -44 to 41 pts
   Home win rate     : 61.2%

   Sample:

,date,away_name,away_score,home_name,home_score,status,home_team_won,winner_name,winner_score,loser_name,loser_score,score_diff
0,2026-02-16,SE Louisiana,53,East Texas A&M,70,Final,1,East Texas A&M,70,SE Louisiana,53,17
1,2026-02-16,Coppin St.,59,SC State,57,Final,0,Coppin St.,59,SC State,57,-2
2,2026-02-16,Louisiana,72,Old Dominion,83,Final,1,Old Dominion,83,Louisiana,72,11
3,2026-02-16,Colgate,58,Boston U.,85,Final,1,Boston U.,85,Colgate,58,27
4,2026-02-16,Bethune-Cook.,86,Jackson St.,91,Final,1,Jackson St.,91,Bethune-Cook.,86,5
5,2026-02-16,Syracuse,64,Duke,101,Final,1,Duke,101,Syracuse,64,37
6,2026-02-16,Grambling St.,63,Prairie View,68,Final,1,Prairie View,68,Grambling St.,63,5
7,2026-02-16,Howard,91,Delaware St.,59,Final,0,Howard,91,Delaware St.,59,-32
8,2026-02-16,Morgan St.,76,NC Central,80,Final,1,NC Central,80,Morgan St.,76,4
9,2026-02-16,Miss Valley St.,55,Alabama St.,92,Final,1,Alabama St.,92,Miss Valley St.,55,37

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Saved:
   Games CSV → /content/drive/MyDrive/Colab Notebooks/ncaab_games_2.csv
              691 rows × 12 cols

   Columns saved:
     • date                      (691 non-null / 691 rows)
     • away_name                 (691 non-null / 691 rows)
     • away_score                (691 non-null / 691 rows)
     • home_name                 (691 non-null / 691 rows)
     • home_score                (691 non-null / 691 rows)
     • status                    (691 non-null / 691 rows)
     • home_team_won             (691 non-null / 691 rows)
     • winner_name               (691 non-null / 691 rows)
     • winner_score              (691 non-null / 691 rows)
     • loser_name                (691 non-null / 691 rows)
     • loser_score               (691 non-null / 691 rows)
     • score_diff                (691 non-null / 691 rows)